### ISSUE TITLE
Releases after `0.1.1` have (strict) install dependency on mypy

### ISSUE THREAD

**Issue by rrjjvv** [hephex/asyncache#12]
I assume the dependency on mypy was accidental (and possibly a side effect of moving to poetry).  Previous to recent updates (before `0.2.0`), the only dependency was on `cachetools` (which is expected/reasonable).

I only noticed this because I was recreating my environment, where my current mypy (`0.990`) conflicts with your stated dependency constraint of `^0.982`.  I'm not a poetry user, but my quick reading (and actual error) both indicate that the constraint effectively locks mypy to that specific version (since mypy doesn't utilize 'patch' releases):
```
ERROR: Cannot install asyncache==0.3.0 and mypy==0.990 because these package versions have conflicting dependencies.
The conflict is caused by:
    The user requested mypy==0.990
    asyncache 0.3.0 depends on mypy<0.983 and >=0.982
```
It would be great if that dependency was removed (or if it's needed for some non-obvious reason, relax the constraint).

**Comment by hephex** [comment]
Yes, the dependency was added there by mistake, it should have been added in the dev dependencies. I'll merge your PR and cut a new release ASAP.

@rrjjvv thanks for sending a patch 💯
